### PR TITLE
Improved form validation example

### PR DESCRIPTION
**Pull request by asavchuk**
Improved form validation example now uses get_it as a dependecy injector, more real worl validation logic, serverside validation runs after local validation passed, inner page added.

### CODE REVIEW

**Review by pavanpodila — APPROVED** [review]

**Comment by ghenry** [comment]
Hi all,

This looks good to merge and close too. Does the project want to recommend get_it or anything like that?

Thanks.

**Comment by asavchuk** [comment]
> Does the project want to recommend get_it or anything like that?

not at all
there are many different possibilities and everyone can choose what is closer to him

**Review by pavanpodila — CHANGES_REQUESTED** [review]
Can you update the docs as well with this example

**Comment by asavchuk** [comment]
> Can you update the docs as well with this example

I'll try.

**Pull request closed without merging**
