### PR TITLE
Routine PR

### LINKED ISSUE #768: Avoid `setState() or markNeedsBuild() called during build` by automatically wait for a frame whenever needed
## Description

During development, I often see the `setState() or markNeedsBuild() called during build` error. Of course, I can avoid it by inserting `addPostFrameCallback` here and there, but some bugs happen under quite strange conditions so it is not easy to do so. In addition, mobx is known to be highly automatic (compared with, e.g. redux), so it is good to hide such details and automatically do the right thing ("wait for a frame").

## Proposed solution

By using https://stackoverflow.com/questions/71367080/automatically-determine-whether-to-wait-for-a-frame-to-avoid-setstate-or-mark or https://stackoverflow.com/a/64702218/4619958, we may do the following: 

* Whenever possible, it calls setState directly. Thus, we do not have a one-frame latency.
* If not possible (i.e. direct setState will lead to the error above), it waits for a frame and setState then. If needed, we can warn or log to tell the user this happens.

## Reproducible sample (mobx generated code included)

Here is a minimal reproducible sample that is simplified from a real-world example in my app in production.

Steps:

* open app
* click the button
* see error

Logs:

```shell
Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
Restarted application in 397ms.
flutter: One.build
flutter: One.Observer.build
flutter: One.build
flutter: One.Observer.build
flutter: TwoChild.initState
flutter: Store.fetch set to pending
flutter: TwoChild.build
flutter: TwoChild.Observer.build

======== Exception caught by flutter_mobx ==========================================================
The following MobXCaughtException was thrown From reaction of Observer
#3      One.build (package:yplusplus/main.dart:52:9) of type StatelessObserverElement.:
setState() or markNeedsBuild() called during build.
This Observer widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Observer
The widget which was currently being built when the offending call was made was:
  Observer

When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4424:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4439:6)
#2      ObserverElementMixin.invalidate (package:flutter_mobx/src/observer_widget_mixin.dart:71:24)
#3      ReactionImpl._run (package:mobx/src/core/reaction.dart:117:22)
#4      ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:351:18)
#5      ReactiveContext.runReactions (package:mobx/src/core/context.dart:325:5)
#6      ReactiveContext.endBatch (package:mobx/src/core/context.dart:155:7)
#7      ActionController.endAction (package:mobx/src/core/action.dart:110:9)
#8      AsyncAction._run (package:mobx/src/api/async/async_action.dart:46:16)
#10     AsyncAction.run (package:mobx/src/api/async/async_action.dart:28:26)
#11     _$_MyStore.fetch (package:yplusplus/main.dart:162:32)
#12     _TwoChildState.initState (package:yplusplus/main.dart:93:18)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#28     _invoke (dart:ui/hooks.dart:151:10)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#30     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 4 frames from dart:async)
====================================================================================================
flutter: Store.fetch set to fulfilled
flutter: TwoChild.Observer.build
```

Code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:mobx/mobx.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final store = _MyStore();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            One(store: store),
            Two(store: store),
          ],
        ),
      ),
    );
  }
}

class One extends StatelessWidget {
  final _MyStore store;

  const One({Key? key, required this.store}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print('One.build');
    return Column(
      children: [
        Observer(builder: (_) {
          print('One.Observer.build');
          return Text('One read status: ${store.status}');
        }),
        TextButton(onPressed: () => store.showTwo = true, child: const Text('click me')),
      ],
    );
  }
}

class Two extends StatelessWidget {
  final _MyStore store;

  const Two({Key? key, required this.store}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Observer(builder: (_) {
      if (store.showTwo) {
        return TwoChild(store: store);
      } else {
        return const Text('Two: empty');
      }
    });
  }
}

class TwoChild extends StatefulWidget {
  final _MyStore store;

  const TwoChild({Key? key, required this.store}) : super(key: key);

  @override
  _TwoChildState createState() => _TwoChildState();
}

class _TwoChildState extends State<TwoChild> {
  @override
  void initState() {
    super.initState();
    print('TwoChild.initState');
    widget.store.fetch();
  }

  @override
  Widget build(BuildContext context) {
    print('TwoChild.build');
    return Observer(builder: (_) {
      print('TwoChild.Observer.build');
      return Text('TwoChild read status: ${widget.store.status}');
    });
  }
}

class _MyStore = __MyStore with _$_MyStore;

abstract class __MyStore with Store {
  @observable
  var showTwo = false;

  @observable
  FutureStatus? status;

  @action
  Future<void> fetch() async {
    print('Store.fetch set to pending');
    status = FutureStatus.pending;

    await Future<void>.delayed(const Duration(seconds: 1));

    print('Store.fetch set to fulfilled');
    status = FutureStatus.fulfilled;
  }
}

mixin _$_MyStore on __MyStore, Store {
  final _$_showTwoAtom = Atom(name: '__MyStore.showTwo');

  @override
  bool get showTwo {
    _$_showTwoAtom.reportRead();
    return super.showTwo;
  }

  @override
  set showTwo(bool value) {
    _$_showTwoAtom.reportWrite(value, super.showTwo, () {
      super.showTwo = value;
    });
  }

  final _$_statusAtom = Atom(name: '__MyStore.status');

  @override
  FutureStatus? get status {
    _$_statusAtom.reportRead();
    return super.status;
  }

  @override
  set status(FutureStatus? value) {
    _$_statusAtom.reportWrite(value, super.status, () {
      super.status = value;
    });
  }

  final _$_fetchAsyncAction = AsyncAction('__BaseHttpAction.fetch');

  @override
  Future<void> fetch() {
    return _$_fetchAsyncAction.run(() => super.fetch());
  }

  @override
  String toString() {
    return '''

    ''';
  }
}
```

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close #768

### CODE REVIEW

**Review by pavanpodila — CHANGES_REQUESTED** [review]
Need to write some unit tests to ensure this behavior is working as expected

**Comment by fzyzcjy** [comment]
Agree. I will do that.

**Comment by fzyzcjy** [comment]
Tests does work. If I comment out the `if (shouldWait)` logic in `_markNeedsBuildImmediatelyOrDelayed`, I see:

```
(base) ➜  flutter_mobx git:(master) ✗ flutter test
00:02 +17: /Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart: StatefulObserverWidget can be subclassed                        
No observables detected in the build method of ConstStatefulObserver
00:02 +18: /Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart: The `setState() or markNeedsBuild() called during build` error is resolved
One.build
One.Observer.build
TwoChild.initState
Store.fetch set to pending
TwoChild.build
TwoChild.Observer.build
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
setState() or markNeedsBuild() called during build.
This Observer widget cannot be marked as needing to build because the framework is already in the
process of building widgets. A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Observer
The widget which was currently being built when the offending call was made was:
  Observer

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4424:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4439:6)
#2      ObserverElementMixin._markNeedsBuildImmediatelyOrDelayed (package:flutter_mobx/src/observer_widget_mixin.dart:103:5)
#3      ObserverElementMixin.invalidate (package:flutter_mobx/src/observer_widget_mixin.dart:75:24)
#4      ReactionImpl._run (package:mobx/src/core/reaction.dart:117:22)
#5      ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:351:18)
#6      ReactiveContext.runReactions (package:mobx/src/core/context.dart:325:5)
#7      ReactiveContext.endBatch (package:mobx/src/core/context.dart:155:7)
#8      ActionController.endAction (package:mobx/src/core/action.dart:110:9)
#9      AsyncAction._run (package:mobx/src/api/async/async_action.dart:46:16)
#11     AsyncAction.run (package:mobx/src/api/async/async_action.dart:28:26)
#12     _$_ObserverRebuildTestMyStore.fetch (file:///Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart:460:32)
#13     _ObserverRebuildTestTwoChildState.initState (file:///Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart:390:18)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#21     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1128:19)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#25     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#28     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#29     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#30     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:668:23)
#31     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:662:38)
#34     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#35     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:662:27)
#36     main.<anonymous closure> (file:///Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart:242:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

The test description was:
  The `setState() or markNeedsBuild() called during build` error is resolved
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +18 -1: /Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart: The `setState() or markNeedsBuild() called during build` error is resolved [E]
  Test failed. See exception logs above.
  The test description was: The `setState() or markNeedsBuild() called during build` error is resolved
  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test (but after the test had completed):
Expected: exactly one matching node in the widget tree
  Actual: _TextContainingFinder:<zero widgets with text containing One read status:
FutureStatus.pending (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:137:31)
#1      _expect (package:test_api/src/expect/expect.dart:132:3)
#2      expect (package:test_api/src/expect/expect.dart:46:3)
#3      expect (package:flutter_test/src/widget_tester.dart:455:16)
#4      main.<anonymous closure> (file:///Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart:244:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +21 -1: Some tests failed.    
```

On the other hand, with that logic:

```
(base) ➜  flutter_mobx git:(master) ✗ flutter test
00:04 +17: /Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart: StatefulObserverWidget can be subclassed                        
No observables detected in the build method of ConstStatefulObserver
00:04 +18: /Users/tom/RefCode/mobx.dart/flutter_mobx/test/flutter_mobx_test.dart: The `setState() or markNeedsBuild() called during build` error is resolved
One.build
One.Observer.build
TwoChild.initState
Store.fetch set to pending
TwoChild.build
TwoChild.Observer.build
One.Observer.build
00:04 +22: All tests passed!

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@all-contributors add @fzyzcjy for code, doc

**Pull request merged**
