### PR TITLE
Adds @readonly annotation support to mobx_codegen

### PR DESCRIPTION
**Pull request by Ascenio**
Continuation of #647.
Replacement of #630.

### CODE REVIEW

**Comment by pavanpodila** [comment]
Now that the branch is merged into master, lets make the PR into master

**Comment by Ascenio** [comment]
So, should I make another to master? I thought you could change the target branch of the PR.

**Comment by Ascenio** [comment]
Oh, I can too, that's nice, didn't know about that.

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@Ascenio, I think you should also create a PR for the docs and describe an example where `@readonly` would be useful.

**Comment by pavanpodila** [comment]
@all-contributors add @Ascenio for code

**Pull request merged**
