### PR TITLE
Observer with excluded child

### PR DESCRIPTION
**Pull request by subzero911**
Sometimes it's nice to have an optional `child` parameter, so you can exclude child branch from re-render and improve performance.
This technique is used in AnimatedBuilder https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html and Consumer https://pub.dev/documentation/provider/latest/provider/Consumer-class.html
I have added a `child` and `builderWithChild` parameters to Observer widget for such cases.
I've also added a test case for it.

Solves https://github.com/mobxjs/mobx.dart/issues/551

---
## Pull Request Checklist

- [x] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [x] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [x] Add the necessary **unit tests** to ensure the coverage does not drop
- [x] Update the **Changelog** to include all changes made in this PR, organized by version
- [x] Run the **`melo run set_version` command** from the root directory
- [x] Include the **necessary reviewers** for the PR
- [ ] Update the docs if there are any API changes or additions to functionality

### CODE REVIEW

**Comment by subzero911** [comment]
I experimented more and I found that it's enough to put your subtree out of immediate context (using `Builder`, for example), and it will be excluded from rebuild. So we don't need this "child" parameter.
It's my bad, and I'll close this.
Gotta add a test showing this behaviour in a future PR.

**Comment by amondnet** [comment]
Hi @subzero911, thank you for your contribution, but what are some examples of when this feature is needed?

**Comment by subzero911** [comment]
@amondnet honestly, I can't come up with any real usecases for this feature 😄

**Comment by subzero911** [comment]
It's crucial for AnimatedBuilder as it re-renders the widget every frame. And if I have some heavy child, I may want to exclude it from being re-rendered.
But Observer is mostly about one-shot rebuilds, it's not intended for animations or continious rebuilds.

**Pull request closed without merging**
