### PR TITLE
Allow users to bypass observability system for performance; Avoid unnecessary observable notifications of `@observable` fields of `Store`s; Fix Reaction lacks toString, so cannot see which reaction causes the error; Add StackTrace to reactions in debug mode to easily spot which reaction it is

### LINKED ISSUE #855: Avoid unnecessary observable notifications of `@observable` fields of `Store`s
## Question

Is it a deliberate/intended feature? If not, I will PR and fix it.

## Description

Say we have a toy store:

<details>

```
class UserSettingStore = _UserSettingStore with _$UserSettingStore;

abstract class _UserSettingStore with Store {
  @observable
  String setting = 'hello';
}

// auto generated

mixin _$UserSettingStore on _UserSettingStore, Store {
  late final _$settingAtom =
      Atom(name: '_UserSettingStore.setting', context: context);

  @override
  String get setting {
    _$settingAtom.reportRead();
    return super.setting;
  }

  @override
  set setting(String value) {
    _$settingAtom.reportWrite(value, super.setting, () {
      super.setting = value;
    });
  }
}
```

</details>

Notice that, if we assign the same value to it, say, `store.setting = 'hello'; store.setting = 'hello';`, it will *still* trigger notifications to downstreams. This is very insufficient.

On the contrary, IMHO if we have Observable or Computeds, it will auto notice the content it unchanged, and thus not notify any downstream.

--- 

Hi I wonder whether this is deliberately designed like that, or there is a reason why we need the current behavior? Thanks!

Not sure whom to cc, but based on ownership and activities, maybe /cc @pavanpodila @amondnet

### LINKED ISSUE #857: Add `disposeValue` callback to `Computed`, such that old values can be properly disposed

### LINKED ISSUE #858: Allow users to bypass observability system for performance
fixed by https://github.com/mobxjs/mobx.dart/pull/844

The issue is here just to make it complete - e.g. in flutter/flutter repo, any PR should have >=1 related issue. I accidentically created that PR w/o any issues.

### LINKED ISSUE #859: Add `Computed.dispose()` method, which disposes existing cached value

### LINKED ISSUE #864: Reaction lacks toString, so cannot see which reaction causes the error; Add StackTrace to reactions in debug mode to easily spot which reaction it is
Example error message I see:

```
Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Instance of 'ReactionImpl' s=#0      ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:344:9)
#1      ReactiveContext.runReactions (package:mobx/src/core/context.dart:325:5)
#2      ReactiveContext.endBatch (package:mobx/src/core/context.dart:155:7)
#3      ActionController.endAction (package:mobx/src/core/action.dart:110:9)

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close #857 
Close #858 
Close #859
Close #855
Close #864

## Pull Request Checklist

- [ ] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [ ] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [ ] Add the necessary **unit tests** to ensure the coverage does not drop
- [ ] Update the **Changelog** to include all changes made in this PR
- [ ] Run the **`set:versions` command** using `npm` or `yarn`. You can find this command in the `package.json` file in the root directory
- [ ] Include the **necessary reviewers** for the PR
- [ ] Update the docs if there are any API changes or additions to functionality

### CODE REVIEW

**Comment by fzyzcjy** [comment]
p.s. I may not merge this before PRs like https://github.com/mobxjs/mobx.dart/pull/842 is merged, since otherwise my master branch will be destoryed

**Review by amondnet — CHANGES_REQUESTED** [review]
1. Please add a changelog and version bump for the mobx package.
2. Need some more unit tests in places where Codecov has flagged.

```dart
    test('bypass observable system', () {
      final list = ObservableList<int>();
      var count = -1;

      expect(list.nonObservableInner.length, 0);

      final d = autorun((_) {
        count = list.nonObservableInner.length;
      });

      expect(count, equals(0));

      list.add(20);
      expect(count, equals(0));
      d();
    });
```

**Comment by fzyzcjy** [comment]
> Add onDispose callback to Computed, such that old values can be properly disposed

feature implemented, test added, and passed

**Comment by fzyzcjy** [comment]
@amondnet tests added

**Comment by fzyzcjy** [comment]
test reproduced #855

image

**Comment by fzyzcjy** [comment]
Revert "dispose"-related features according to #860

**Review by amondnet — APPROVED** [review]
LGTM

**Comment by ghenry** [comment]
Hi all,

If this is in a "LGTM" state, is it just awaiting for @pavanpodila to approve or can someone else help with the load?

Thanks.

**Comment by amondnet** [comment]
Hi, @fzyzcjy 
I add the missing tests, bump the version and write the changelog. https://github.com/mobxjs/mobx.dart/pull/894

**Pull request closed without merging**
