### PR TITLE
Include a set reference in ObservableSet change notifications

### PR DESCRIPTION
**Pull request by shyndman**
This mimics the other Observable collections.

https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/api/observable_collections/observable_list.dart#L380
https://github.com/mobxjs/mobx.dart/blob/master/mobx/lib/src/api/observable_collections/observable_map.dart#L210

### CODE REVIEW

**Comment by pavanpodila** [comment]
Coverage has dropped a bit

**Comment by shyndman** [comment]
So I'm looking at the diff...how could coverage have dropped? There are no new branches.

**Comment by shyndman** [comment]
Oh, I see, it's the `asserts` in the initializer list. That seems alright, doesn't it?

**Comment by pavanpodila** [comment]
How about a quick test just on the `SetChange` class without providing the required values. That would throw the `AssertionError` and we have full coverage?

**Comment by shyndman** [comment]
Done

**Comment by shyndman** [comment]
Oops, still figuring out how to use GH the way I'd like. Kicking off a new PR.

**Comment by shyndman** [comment]
Continued in #276

**Pull request closed without merging**
