### PR TITLE
add issue_tracker links to pubspec

### PR DESCRIPTION
**Pull request by MaikuB**
pub.dev recently changed the logic for showing the View/report issues link 

---
## Pull Request Checklist

- [x] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [x] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [ ] Add the necessary **unit tests** to ensure the coverage does not drop
- [x] Update the **Changelog** to include all changes made in this PR
- [x] Run the **`set:versions` command** using `npm` or `yarn`. You can find this command in the `package.json` file in the root directory
- [x] Include the **necessary reviewers** for the PR
- [ ] Update the docs if there are any API changes or additions to functionality

### CODE REVIEW

**Review by fzyzcjy — APPROVED** [review]
LGTM

**Comment by MaikuB** [comment]
Thanks for the quick response @fzyzcjy. Been a while since I worked on the repo and although it's a small change, wondering if this needs to wait on @pavanpodila or should I just merge this in?

**Comment by fzyzcjy** [comment]
> wondering if this needs to wait on @pavanpodila or should I just merge this in?

Well indeed I also dnk... Maybe just ask him - he is the owner.

**Comment by MaikuB** [comment]
> Well indeed I also dnk... Maybe just ask him - he is the owner.

No worries, he is tagged on PR too :)

**Comment by pavanpodila** [comment]
Ya in future you folks have the power to merge if you think the PR is complete, does not lower coverage and improves overall health of the project.

In fact, why don't you merge @fzyzcjy 👍

**Comment by MaikuB** [comment]
Cool, I do have permissions too from being added to team a while back so will merge it in :)

**Comment by fzyzcjy** [comment]
> In fact, why don't you merge @fzyzcjy 👍

@pavanpodila Since you own the repo :)

I know it now and will do so in the future

**Pull request merged**
