### PR TITLE
feat: add scheduler option to autorun and reaction

### PR DESCRIPTION
**Pull request by amondnet**
Describe the changes proposed in this Pull Request.

Add `scheduler` to `reaction` and `autorun` to allow customizing the scheduler used to schedule the reaction.

https://mobx.js.org/reactions.html#scheduler-_autorun-reaction_

---
## Pull Request Checklist

- [x] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [x] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [x] Add the necessary **unit tests** to ensure the coverage does not drop
- [x] Update the **Changelog** to include all changes made in this PR, organized by version
- [x] Run the **`melos run set_version` command** from the root directory
- [x] Include the **necessary reviewers** for the PR
- [x] Update the **docs** if there are any API changes or additions to functionality

### CODE REVIEW

**Comment by amondnet** [comment]
@pavanpodila Could you please review the code?

**Review by pavanpodila — APPROVED** [review]
LGTM

**Comment by pavanpodila** [comment]
I would suggest adding to the Docs as well...its probably a bit stale with the host of changes that have happened in the last year

**Comment by pavanpodila** [comment]
Great work btw... @amondnet !

**Pull request merged**
