### PR TITLE
result of Observable is not a String, but an Observable

### PR DESCRIPTION
**Pull request by vandadnp**
Thank you so much for MobX, I absolutely love it and really appreciate all the hard work that has gone into creating it.

While reading the docs I noticed that we are assigning the result of Observable into a String, and that just won't compile. So I fixed that by replacing "String" with "final"

### CODE REVIEW

**Review by fzyzcjy — APPROVED** [review]
LGTM

**Comment by vandadnp** [comment]
@fzyzcjy thank you, it seems like one of the checks didn't pass, any idea what that is?

**Comment by fzyzcjy** [comment]
Seems not a problem of your PR. no worries

**Comment by vandadnp** [comment]
Alright, thank you

**Review by amondnet — APPROVED** [review]
LGTM

**Review by pavanpodila — APPROVED** [review]

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@all-contributors add @vandadnp  for doc

**Pull request merged**
