### PR TITLE
withBuiltChild fix

### PR DESCRIPTION
**Pull request by subzero911**
I fixed `Observer.withBuiltChild` constructor.
I removed runtime asserts and unneeded nullables. So now it's neat.

I also added an example to the docs.

---
## Pull Request Checklist

- [x] If the changes are being made to code, ensure the **version in `pubspec.yaml`** is updated. 
- [x] Increment the **`major`/`minor`/`patch`/`patch-count`**, depending on the complexity of change
- [x] Add the necessary **unit tests** to ensure the coverage does not drop
- [x] Update the **Changelog** to include all changes made in this PR, organized by version
- [x] Run the **`melos run set_version` command** from the root directory
- [x] Include the **necessary reviewers** for the PR
- [x] Update the **docs** if there are any API changes or additions to functionality

### CODE REVIEW

**Comment by subzero911** [comment]
@pavanpodila @amondnet

**Comment by subzero911** [comment]
image

@pavanpodila 
CI/CD says don't use explicit types for constructor super parameters. But I see nothing bad with it. You'd better set less strict linter rules.

Anyway, it doesn't relate to the current MR and should be fixed in a separate MR.

**Comment by pavanpodila** [comment]
> image
> 
> 
> 
> @pavanpodila 
> 
> CI/CD says don't use explicit types for constructor super parameters. But I see nothing bad with it. You'd better set less strict linter rules.

I'm using default rules with no overrides. These are the ones recommended by Flutter itself

**Comment by pavanpodila** [comment]
We should also upgrade the lints packages

**Comment by subzero911** [comment]
image

It isn't shown as an error in the IDE, but CI/CD fails on this line for some reason.

**Comment by subzero911** [comment]
Anyway, it's out of scope of the current MR. It should be done in a separate MR.

**Pull request closed without merging**
