### PR TITLE
Add code generation support for the @store annotation

### PR DESCRIPTION
**Pull request by shyndman**
There are still two remaining tasks:
* [ ] JsonSerializable test (might be moved to separate PR)
* [x] Generated subclass should include constructors from user-defined store class

### CODE REVIEW

**Comment by pavanpodila** [comment]
Let's move the JSON test to a separate PR, but get the subclass constructor part in.

**Comment by shyndman** [comment]
kk. I'm heading to a meeting, but I'll be back in a few hours.

**Comment by shyndman** [comment]
@pavanpodila, got the constructor generation code in. PTAL.

**Comment by shyndman** [comment]
Also, excellent work on all the method template stuff. Writing the constructor overrides was a piece of cake.

**Comment by pavanpodila** [comment]
Credit for the templates go to @katis

**Comment by shyndman** [comment]
So how's it look? Are we good to go?

**Comment by shyndman** [comment]
Mind if we push another alpha? I want to get this going in our project.

**Comment by pavanpodila** [comment]
I have published the packages on [pub.dev](https://pub.dev/packages?q=mobx).

```
mobx: 0.3.6
mobx_codegen: 0.3.5
```

**Comment by shyndman** [comment]
You're welcome. Thanks!

**Comment by shyndman** [comment]
Hey, @pavanpodila, I've found some problems. Most are minor, but here's the big one:

If a `@store` references other stores in its `@observable`s or whatever, their types are not recognized and get generated as dynamic.

**Comment by shyndman** [comment]
Which makes sense. The type is generated, and isn't yet available to the analyzer.

**Comment by shyndman** [comment]
This isn't great. I'm going to sleep on it.

**Comment by shyndman** [comment]
If we're willing to get a little hacky, I can fix this. At the same time I can make it work with dart:ui types directly.

Do you have a chat channel or something? GH comments are too low bandwidth.

**Comment by shyndman** [comment]
We might also want to move this back into a branch, and get it off pub. It's not ready for prime-time.

**Comment by pavanpodila** [comment]
> If we're willing to get a little hacky, I can fix this. At the same time I can make it work with dart:ui types without a need for a subclass.
> 
> Do you have a chat channel or something? GH comments are too low bandwidth.

Let's do over Gitter with private messages: https://gitter.im/mobxjs/mobx.dart

**Comment by pavanpodila** [comment]
> We might also want to move this back into a branch, and get it off pub. It's not ready for prime-time.

That's fine we can keep it there as undocumented feature for now. When its ready, we can add it to the docs on the site

**Pull request merged**
