### PR TITLE
Update provider example to 2.0

### PR DESCRIPTION
**Pull request by rrousselGit**
With the 2.0-dev version of `provider`, `StatefulProvider` and `Provider` fused.

This PR reflects this change.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Good point, I forgot about them

**Comment by rrousselGit** [comment]
The existing `pubspec.yaml` doesn't have a version constraint so I assumed it wasn't needed.
But I added it

**Comment by pavanpodila** [comment]
Ah ok. My bad. I think we are ok without the version.

**Comment by rrousselGit** [comment]
Actually, I've just tested and it seems to be required.
It seems that `provider:` resolves to the latest stable release. So it resolves to `1.6.1` instead of `2.0.0-dev`

**Comment by pavanpodila** [comment]
trying to merge, but looks like some glitch in CircleCI, which is stopping it

**Comment by rrousselGit** [comment]
What can I do to unlock the CI?

**Comment by pavanpodila** [comment]
How about pushing some minor change to retrigger?

**Comment by rrousselGit** [comment]
It doesn't seem to work.  🤷‍♂

**Comment by pavanpodila** [comment]
How about closing this PR and creating a new one with a different branch name?

**Pull request closed without merging**
