### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by katis**
Moved `mobx` package files to mobx/, used `mono_repo` to generate travis configs.

### CODE REVIEW

**Comment by rrousselGit** [comment]
I think we should test to generate a flutter configuration before merging it. As it may be something non-trivial to do using mono_repo

**Comment by pavanpodila** [comment]
@katis can we try having a flutter configuration?

**Comment by katis** [comment]
Unfortunately can't get mono_repo to work with a flutter package. I need to do some build scripts manually for now.

**Comment by rrousselGit** [comment]
I have an example of a travis-ci for flutter here: https://github.com/rrousselGit/flutter_hooks/blob/master/.travis.yml

It's not documented, but you can have the following in mono_pkg.yaml:

```yaml
stages:
  - some_stage_name:
    - command: do whatever you want
```

It should be doable to copy paste the commands from the previous `.travis.yaml` and prefix them by `command:` for it to work with `mono_repo`

**Comment by katis** [comment]
But I guess "monorepo pub get" and "monorepo pub upgrade" wont work?

**Comment by rrousselGit** [comment]
Ah – Indeed, didn't think of that. 
I'll see if I can make a PR for it. It shouldn't be too difficult from my memory

**Comment by rrousselGit** [comment]
https://github.com/dart-lang/mono_repo/pull/118

I made a PR to support `mono_repo pub get` for flutter projects.

**Comment by katis** [comment]
I'll merge this, and then start with the `flutter_mobx` project. I think we'll get by for a while without `mono_repo pub`

**Pull request merged**
