### PR TITLE
Update to analyzer 2.0.0

### PR DESCRIPTION
**Pull request by davidmartos96**
I had to update how the function typedefs are handled to accommodate to the new version.

### CODE REVIEW

**Review by pavanpodila — COMMENTED** [review]
Looks good. Can you also update the build_runner in mobx  and see if there are any issues ?

**Comment by davidmartos96** [comment]
I had trouble resolving the dependencies for `mobx_examples` because `meta` 1.7.0 (used by `analyzer` 2.0.0) is not compatible with `flutter_test` in stable, which uses `meta` 1.3.0

**Comment by carlosfiori** [comment]
Fixes #688

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@all-collaborators add @davidmartos96 for code

**Comment by pavanpodila** [comment]
@all-contributors add @davidmartos96 for code

**Pull request merged**
