### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by JEuler**
Fix for https://github.com/mobxjs/mobx.dart/issues/357

### CODE REVIEW

**Comment by shyndman** [comment]
Oops, not quite. We need a version bump in this pubspec as well. Let's go to 0.3.12. 

Mind sending that this way? (we need a contributor and approver — I can't do both parts)

**Comment by JEuler** [comment]
Whoops, let me create new PR with this.

вс, 29 дек. 2019 г. в 15:30, Scott Hyndman <notifications@github.com>:
>
> Oops, not quite. We need a version bump in this pubspec as well. Let's go to 0.3.12.
>
> Mind sending that this way? (we need a contributor and approver — I can't do both parts)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Terekhin Ivan

**Comment by hramnathnayak** [comment]
I guess we should update the dependency on flutter_mobx pubspec.yaml as well.... I can create a PR

**Comment by hramnathnayak** [comment]
Also update the verssion on mobx_codegen.dart file... adding to my PR

**Comment by hramnathnayak** [comment]
created #364

**Comment by JEuler** [comment]
Okay! And please release all this on dart pub, because now the build is still broken with recent versions. :)

**Comment by hramnathnayak** [comment]
@pavanpodila @JEuler @shyndman   - Please review #364 and let me know if anything needs to be changed here. Thanks !

**Pull request merged**
