### PR TITLE
Add dispose method to Store

### LINKED ISSUE #176: Should Store interface have a `dispose` method?
This is about the `Store` class from: https://github.com/mobxjs/mobx.dart/blob/5619ed2e21d717072da50febe9615fe2e6aee8e2/mobx/lib/src/api/annotations.dart#L25

This class is used as a base class for all custom mobx stores. As such, it is logical for libraries built on the top of `Mobx` to use the `Store` interface for object constraints.

Example:

```dart
class Foo<T extends Store> {
  // TODO: do something Mobx specific with T
}
```

At the same time, while many stores don't need to be disposed of, many do due to internal reactions like so:

```dart
class MyStore implements Store {
  ReactionDisposer _disposer;

  MyStore() {
    _disposer = when(something);
  }

  void dispose() {
    _disposer();
  }
}
```

____

The problem is, if library makers want to interact with stores (for example controlling when they are created/disposed), then these libraries won't be able to correctly dispose of stores with internal reactions.

So if `Store` looked more like this:

```dart
abstract class Store {
  void dispose() {}
}
```

That would allow libraries to make something like this:

```dart
class Example<T extends Store> extends StatefulWidget {
  const Example({Key key, this.builder}) : super(key: key);

  final T Function() builder;

  @override
  _ExampleState<T> createState() => _ExampleState<T>();
}

class _ExampleState<T extends Store> extends State<Example<T>> {
  T store;

  @override
  void initState() {
    super.initState();
    store = widget.builder();
  }

  @override
  void dispose() {
    store.dispose();
    super.dispose();
  }
}
```

Where this class handles both creation and cleaning up of a `Store`.

This is something that I'd like as an attempt to solve https://github.com/mobxjs/mobx.dart/issues/161 with `provider`.

### PR DESCRIPTION
**Pull request by rrousselGit**
closes #176

### CODE REVIEW

**Comment by rrousselGit** [comment]
Note that this is breaking change even without the `implements` -> `with` change.

**Comment by rrousselGit** [comment]
Another point is, we could allow both:

- `class MyStore with Store`
- `class MyStore implements Store { void dispose() {} }`

With the current changes, only the former is possible.

We could allow both, but I think it is interesting to forces using `with`. This way in the future if other methods are added on `Store`, this won't be a breaking change.

**Comment by rrousselGit** [comment]
What's the purpose of `Store` interface then?

**Comment by pavanpodila** [comment]
I was thinking of isolating the "dispose" behavior into an interface. But looks like this is an intrinsic behavior and should really be part of the interface/mixin. Someone else was also asking about a `toString` implementation (#174). I guess it would be easier to do it then.

Since this is a breaking change, we should change our version as well accordingly.

**Comment by rrousselGit** [comment]
I don't understand how this is related to `toString`.

Not do I understand what I have to do now haha

**Comment by pavanpodila** [comment]
LoL. My question was about versioning. Since it's a breaking change we will need some docs on the change. I'll try it out today and then merge. Busy with some client work.

**Comment by talamaska** [comment]
Hi, I'm not sure what happened with this change, but it seems in 2021 this is gone from the Store mixin.
Should I just implement a normal action called dispose and handle whatever I need to dispose?

**Comment by anton-brass** [comment]
what is the answer of @talamaska  question?

**Pull request merged**
