### PR TITLE
Added TodoJsonMapper example

### PR DESCRIPTION
**Pull request by felipeleon73**
I created a new Todos example as requested.
I also had to make a change also to github_store.dart otherwise I could not compile ... ignore it if you want.

### CODE REVIEW

**Comment by pavanpodila** [comment]
@felipeleon73 Let me know if you can finish this up or should I pick it

**Comment by felipeleon73** [comment]
I'm still doing some tests ... dart json mapper needed some modifications to work properly with mobx flutter and @k-paxian is kindly giving me a huge hand. As soon as the tests are finished, I promise to intervene on the PR

**Comment by pavanpodila** [comment]
Awesome :-)

**Comment by deadsoul44** [comment]
Any update? How about the new package dart_json_mapper_mobx?

**Comment by pavanpodila** [comment]
> Any update? How about the new package dart_json_mapper_mobx?

I am a bit busy right now but can look into it later this week

**Comment by k-paxian** [comment]
I guess this PR could be declined in favor of #440

**Pull request closed without merging**
