### PR TITLE
Fix for #681: ObservableStream.value throws Exception when data is null

### PR DESCRIPTION
**Pull request by moritz-weber**

### CODE REVIEW

**Review by pavanpodila — CHANGES_REQUESTED** [review]
Can we get a test as well to make sure this is working? You can use the other tests for reference

**Comment by moritz-weber** [comment]
Writing the test is not as easy as I thought.
The existing test `providing no initialValue sets initial status to waiting` covers the case that I want to test.
However, it doesn't throw an exception as the tests are run with Dart 2.10 (from what I understand).

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@moritz-weber Please do a merge from master and refresh this PR. I made a few fixes in master for the analysis errors. That should clear the Github checks.

**Review by pavanpodila — APPROVED** [review]

**Comment by pavanpodila** [comment]
@all-contributors add @moritz-weber for code

**Pull request merged**
